CI Update

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -65,3 +65,16 @@ jobs:
           files: coverage.xml
           fail_ci_if_error: false
         continue-on-error: true
+  
+  summary:
+    name: CI passed
+    runs-on: ubuntu-latest
+    needs: [lint, tests]
+    if: always()
+    steps:
+      - name: Check all jobs passed
+        run: |
+          if [[ "${{ needs.lint.result }}" == "failure" || "${{ needs.tests.result }}" == "failure" ]]; then
+            echo "CI failed" && exit 1
+          fi
+          echo "CI passed"
